[build]
command = "npm run build"  # Or the command to build your project
publish = "dist/public"
functions = "netlify/functions"

[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/:splat"

[dev]
command = "npm run dev"
port = 3001  # Change the port to a different value if needed
